#!/usr/bin/env bash
TAG=$1
SR_VERSION=$2
CONFLUENT_VERSION=$3
KAFKA_VERSION=$4
LENSES_CLI_VERSION=$5

if [[ -z "${TAG}" ]]; then
    echo "No tag provided"
    echo "Usage: ./build-dockers tag sr-version confluent-version kafka-version cli-version"
    exit 1
fi

if [[ -z "${CONFLUENT_VERSION}" ]]; then
    echo "No confluent version provided"
    echo "Usage: ./build-dockers tag sr-version confluent-version kafka-version cli-version"
    exit 1
fi

if [[ -z "${KAFKA_VERSION}" ]]; then
    echo "No CLI version provided"
    echo "Usage: ./build-dockers tag sr-version confluent-version kafka-version cli-version"
    exit 1
fi

if [[ -z "${LENSES_CLI_VERSION}" ]]; then
    echo "No CLI version provided"
    echo "Usage: ./build-dockers tag sr-version confluent-version kafka-version cli-version"
    exit 1
fi

if [[ -z "${SR_VERSION}" ]]; then
    echo "No Stream reactor version provided"
    echo "Usage: ./build-dockers tag sr-version confluent-version kafka-version cli-version"
    exit 1
fi

./kafka-connect-base/build ${SR_VERSION} ${CONFLUENT_VERSION} ${LENSES_CLI_VERSION}
./stream-reactor/build ${TAG} ${SR_VERSION} ${KAFKA_VERSION}