#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TAG=$1
SR_VERSION=$2
CONFLUENT_VERSION=$3
KAFKA_VERSION=$4
REPO=streamreactor

./build-dockers ${TAG} ${SR_VERSION} ${CONFLUENT_VERSION} ${KAFKA_VERSION} ${LENSES_CLI_VERSION}

echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
docker push ${REPO}/stream-reactor-base:${TAG}
docker push ${REPO}/stream-reactor-base

input="stream-reactor/connectors.txt"

while IFS= read -r STREAM_REACTOR_COMPONENT
do
    echo "Publishing ${STREAM_REACTOR_COMPONENT} connector version ${TAG}"
    docker push ${REPO}/${STREAM_REACTOR_COMPONENT}:${TAG}
    docker push ${REPO}/${STREAM_REACTOR_COMPONENT}
done < "$input"
