#!/usr/bin/env bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
COMPONENT="kafka-connect"
TAG="${1}"
CONFLUENT_VERSION="${2}"
SECRET_PROVIDER_VERSION="${3}"
CONNECT_CLI_VERSION="${4}"
CALCITE_LINQ4J_VERSION="1.12.0"
REPO=streamreactor

function die() {
    for m in "${@}"; do
        echo -e "${m}"
    done
    exit 1
}

declare -a ENV_ARRAY=("TAG" "CONFLUENT_VERSION" \
                      "SECRET_PROVIDER_VERSION" \
                      "CONNECT_CLI_VERSION")

echo -e "\n\tChecking Environment"
for e in "${ENV_ARRAY[@]}"; do
    [[ -z "${!e}" ]] && die "\t\tEnv ${e} was not provided"
    echo -e "\t\tEnv ${e} has been set with: ${!e}"
done

echo -e "\n\tBuilding base connect docker\n"
docker build \
    --build-arg CONFLUENT_VERSION="${CONFLUENT_VERSION}" \
    --build-arg SECRET_PROVIDER_VERSION="${SECRET_PROVIDER_VERSION}" \
    --build-arg CONNECT_CLI_VERSION="${CONNECT_CLI_VERSION}" \
    -t ${REPO}/stream-reactor-base:${TAG} \
    -t ${REPO}/stream-reactor-base \
    -f ${DIR}/Dockerfile ${DIR}