#!/usr/bin/env bash

export pid="$(cat /var/run/kc.pid 2>&1)"

function die() {
  for m in "${@}"; do
    echo -e "${m}" 1>&2
  done

  exit 1
}

function get_status() {
  if [[ ! -e "/proc/${pid}" ]]; then
    die "Kafka Connect is not running"
  fi

  rr="$(realpath /proc/${pid}/exe)"
  if [[ "${rr}" == '/usr/lib/jvm/zulu-8-amd64/jre/bin/java' ]]; then
    echo -e "Kafka Connect is running"
  fi
}

function init_kc() {
  if [[ ! -e "/proc/${pid}" && "${rr}" != '/usr/lib/jvm/zulu-8-amd64/jre/bin/java' ]]; then

    ((/etc/confluent/docker/launch >/runtime.log 2>&1) & echo $! > /var/run/kc.pid &)
  
  else
    die "Kafka connect is already running"
  fi
}

function kill_kc() {
  kill -s TERM "${pid}"
}

function restart_kc() {
  kill_kc && init_kc
}

function get_help() {
  echo -e "Usage: ./kc-cli opts"
  echo -e "\t-s\tStatus of Kafka Connect"
  echo -e "\t-t\tTerminate Kafka Connect"
  echo -e "\t-i\tInit Kafka Connect"
  echo -e "\t-r\tRestart Kafka Connect"
  echo -e "\t-v\tView Kafka Connect logs"
  echo -e "\t-g\tDump to stdout Kafka Connect logs"
  echo -e "\t-o\tTail Kafka Connect logs"
}

function view_logs() {
  if [[ -e "/runtime.log" ]]; then
    less /runtime.log
  else
    die "No logs to view. Is the process running?"
  fi

  exit 0
}

function dump_logs() {
  if [[ -e "/runtime.log" ]]; then
    cat /runtime.log
  else
    die "No logs found for Kafka Connect"
  fi

  exit 0
}

function tail_logs {
  if [[ -e "/runtime.log" ]]; then
    tail -f /runtime.log
  else
    die "No logs found for Kafka Connect"
  fi
}

if [[ "${#}" == "0" ]]; then
  get_help
  exit 0
fi

while (( "$#" )); do
  case ${1} in
    "-h" )
      get_help
      exit 0;;
    "-s" )
      get_status;;
    "-i" )
      init_kc;;
    "-t" )
      kill_kc;;
    "-r" )
      restart_kc;;
    "-v" )
      view_logs;;
    "-d" )
      dump_logs;;
    "-o" )
      tail_logs;;
   * )
     die "Invalid option: ${1}" \
     "For options issue: ./kc-cli -h"
     ;;
  esac
  shift 1
done
